### ISSUE TITLE
[Model] Place a table for users to form a circle

### ISSUE THREAD

**Issue by snowymo** [futurerealitylab/immersive-presentation#13]
**Is your feature request related to a problem? Please describe.**
When users enter metaroom, they can see a table and everyone is positioning around the table.

-- @cdefanti feel free to throw anything here --

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cdefanti** [comment]
I added the asset here: https://github.com/futurerealitylab/immersive-presentation/tree/table
However, I have not yet added it into the scene. Should I just add a node containing that geometry, or do we want a more generalized/elegant way to add in objects?

**Comment by cdefanti** [comment]
PR here: https://github.com/futurerealitylab/immersive-presentation/pull/26

**Comment by snowymo** [comment]
Excellent! Feel free to delete the branch if you don't want it anymore.
