### ISSUE TITLE
[Hack] Need a table, need to see name tag, need to sync button state.

### ISSUE THREAD

**Issue by snowymo** [futurerealitylab/immersive-presentation#19]
**Is your feature request related to a problem? Please describe.**
1. want to see a table at the center. @cdefanti 
2. want to see a name tag associated with the user. @KeruWang 
3. want to sync button state that other ppl can see demos together.

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
TBD

**Comment by snowymo** [comment]
@KeruWang @kenperlin 
Considering at least displaying a name for each avatar, my hack idea is that
1) we have an input field on the page for users to type name
2) we real-timely associate the name in that field to the user's _name attribute_
3) we display the _name attribute_ probably on the top of the avatar.

How do you think about it? Could you take care of part 3) since you may be more familiar with displaying text in the corresponding transformation @KeruWang ?

**Comment by KeruWang** [comment]
Yes I can take care of part 3.

**Comment by snowymo** [comment]
> Yes I can take care of part 3.

Excellent. I just add attribute 'name' for class ```Avatar```, see branch ```protocol``` https://github.com/futurerealitylab/immersive-presentation/blob/protocol/js/primitive/avatar.js#L33

**Comment by snowymo** [comment]
@keruwang fill the commit when name tag is done, then I will close this issue.

If we want to improve it visually, we can open another one.
