### ISSUE TITLE
[Bug] Navigation error when rotating with mouse

### ISSUE THREAD

**Issue by snowymo** [futurerealitylab/immersive-presentation#8]
**Describe the bug**
For non-VR users, they can navigate the scene through WSAD and rotate the view when dragging the mouse. However, the rotation is not working correctly when the user is not at the center.

**To Reproduce**
1. Click key D to move self to the far right.
2. Drag the mouse to rotate the view.
3. Now we can see the viewer is being moved when we only want to rotate the view.

**Expected behavior**
What we want is that the viewer's position should not be changed when the mouse is being dragged to rotate the view.

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]

**Additional context**
I guess it is related to the order of your transformation code.

**Comment by snowymo** [comment]
I found that WSAD always moves the viewer to the front, back, left, and right regardless the viewer's orientation. See the video. 

https://user-images.githubusercontent.com/10137769/116835196-7bc34580-ab8f-11eb-83bc-7f62b1d76653.mp4

From 00:06, I've rotated the viewer. However, the way how WSAD works is the same as before rotation. 

From my understanding, navigation should be identical to a first-person camera.

**Comment by KeruWang** [comment]
This is an old bug but I have already fixed that before. I just pull from main and here is how it looks on my side:
https://user-images.githubusercontent.com/54900999/116837641-43c10000-ab99-11eb-83c5-5486a9c3a1fe.mov

I am not sure why this would happen to you. Have you pulled from main?

**Comment by KeruWang** [comment]
https://user-images.githubusercontent.com/54900999/116838445-5a1c8b00-ab9c-11eb-8633-a9f3c494f82b.mov

You mean the WASD is moving the player in the absolute direction regardless of the player's current rotation? This is an old bug, and for now, I don't have this bug on my side. I just pulled from the main again, and it looks alright to me (please see the screen record). I am not sure why you are re-encountering this. Could you try pull from main again?

**Comment by snowymo** [comment]
Yes working now. Maybe cache!
